require_relative 'src/author'
require_relative 'src/genre'
require_relative 'src/label'
require_relative 'src/source'
require_relative 'src/item'

require_relative 'src/movie/movie'
require_relative 'src/movie/preserve_movie'
require_relative 'src/music_album/music_album'
require_relative 'src/music_album/preserve_music_albums'
